### ISSUE TITLE
Clear off cached tokens on logout

### ISSUE THREAD

**Issue by ravidixit** [OfficeDev/Office-365-SDK-for-iOS#47]
What is the method which we can use to clear off the tokens created on login? Am using below method to login

    [authContext acquireTokenWithResource:@"Microsoft.SharePoint" clientId:self.clientID
     redirectUri:self.redirectURI completionBlock:^(ADAuthenticationResult *result)

It seems that it's getting stored in some cache what i require is a way to clear off the cache when the user taps logout and display the default login screen seen when called the above method.

Note: This is not a issue here i want help but could not find a way to label it.

**Comment by dorinsimina** [comment]
You could use the existing sample code:

<code>
id<ADTokenCacheStoring> cache = [ADAuthenticationSettings sharedInstance].defaultTokenCacheStore;
    ADAuthenticationError * error;
    if ([[cache allItemsWithError:&error] count] > 0)
        [cache removeAllWithError:&error];
</code>

**Comment by ravidixit** [comment]
It worked great @dorinsimina  do we have a documentation in place for the SDK I can't find it can you please help me with that?

**Comment by dorinsimina** [comment]
From what I know there is no documentation for the SDK. So my advice is to look at the REST API specifications since this SDK is a very nice wrapper for that. Also you can look carefully at the sample codes offered and to the test methods.

https://msdn.microsoft.com/en-us/office/office365/api/api-catalog

Also if a specific resource is not accessible or some parts not implemented you can easily extend the SDK or make the REST API calls on your own.
